// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhwmtvxzvlgaoikclckc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZod210dnh6dmxnYW9pa2NsY2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMDkxMDgsImV4cCI6MjA3MDg4NTEwOH0.7IZz49DQXsk9I_80zhCdyR6tbMcd9R8qoiIEO_eplpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});